### PR TITLE
Profile Algorithm pull

### LINKED ISSUE #22: Create portfolio-to-personality profile algorithm
Create portfolio to personality profile algorithm
Under Story #4

### LINKED ISSUE #24: Algorithm Inputs and Outputs
Figure out inputs and outputs of algorithm. Crucial for #4 and #5

### PR DESCRIPTION
**Pull request by elrodrigues**
This closes #22, closes #24 

Changes:
- Added generate_profile algorithm

### CODE REVIEW

**Comment by elrodrigues** [comment]
Notes:
Market Input
**MB** is market-to-book ratio
**SIZE** is capitalization size

Personality Output
**EXPEXT** is "exploratory excitability" and extravagance
**IMPDIS** is impulsiveness and disorderliness
**ATTDEP** is attachment and dependence
**SENTIM** is sentimality

**Comment by elrodrigues** [comment]
MB_e = 0.026e + 0.20709 - 0.3626 + 0.000 + 1.892
= 0.026e + 1.73649; e = 38.46 * (MB - 1.73639)
MB_i = 0.27716 + 0.027i - 0.3626 + 0.000 + 1.892
= 0.027i + 1.80656; i = 37.037 * (MB - 1.80656)
MB_s = 0.27716 + 0.20709 - 0.074s + 0.000 + 1.892
=  2.37625 - 0.074s; s = 13.514 * (2.37625 - MB)
MB_a = 0.27716 + 0.20709 - 0.3626 + 0.000a + 1.892
= null; a = 0
SIZE_e = 854e - 7700.68 + 83.3 - 9292 + 12785
= 854e - 4124.38; e = 0.0012*(SIZE + 4124.38)
SIZE_i = 9103.64 - 1004i + 83.3 - 9292 + 12785
= -1004i + 12679.64; i = 0.001*(12679.64 - SIZE)
SIZE_s = 9103.64 - 7700.68 + 17s - 9292 + 12785
= 17s + 4895.96; s = 0.059*(SIZE - 4895.96)
SIZE_a = 9103.64 - 7700.68 + 83.3 - 1010a + 12785
= -1010a + 14271.26; a = 0.001*(14271.26 - SIZE)

e = 19.23(MB - 1.73639) + 0.0006(SIZE + 4124.38)
i = 18.5185(MB - 1.80656) + 0.0005(12679.64 - SIZE)
s = 6.757(2.37625 - MB) + 0.0295(SIZE - 4895.96)
a = 0 + 0.0005(14271.26 - SIZE)

**Comment by elrodrigues** [comment]
TODO: add logistic function for smooth results

**Comment by bryant-ta** [comment]
Wow algorithm looks snazzy!

Why do we split finnhub_client into sandbox and real version? I think sandbox's 60 calls/min should be enough for everything?

**Comment by elrodrigues** [comment]
> Why do we split finnhub_client into sandbox and real version? I think sandbox's 60 calls/min should be enough for everything?

Good point. I separated them when testing. I'll merge them now.

**Review by bryant-ta — APPROVED** [review]
Looks good with the fix.

**Review by daniel77chen — COMMENTED** [review]
yes, seems good to me now as well.

**Pull request merged**
